version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_ppi
    ports:
      - "8123:8123"   # HTTP port
      - "9000:9000"   # Native port
    volumes:
      - ./data:/var/lib/clickhouse
      - ./config:/etc/clickhouse-server
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse_secret
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  python_loader:
    build: 
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      - clickhouse
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data 